services:
  server:
    build:
      dockerfile: Dockerfile.app
      context: .
      target: ${TARGET}
    volumes:
      - ./db:/usr/src/app/db
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
      - SESSION_SECRET
    env_file:
      - ./.env
  api:
    build:
      dockerfile: Dockerfile.api
      context: .
      target: ${TARGET}
    volumes:
      - ./db:/usr/src/app/db
      - ./src:/usr/src/app/src
    ports:
      - 3001:3000
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
    env_file:
      - ./.env

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - '3002:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: